# Generated by Django 4.2.7 on 2023-11-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_checkedtarefas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='status',
        ),
        migrations.AlterField(
            model_name='checkedtarefas',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
